export const movies= [{ name:"Dungeons & Dragons",
price:"669",
starCount:0,
rating:"8.3",
about:"A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people in this hilarious and action-packed adventure.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/81vw9lxEUZL._AC_UL480_FMwebp_QL65_.jpg",
},
{ name:"Spy",
price:"219",
starCount:0,
rating:"5.7",
about:"After receiving the news of the death of his elder brother Subash, who worked for R&AW, Jay sets out on a mission to find out what happened leading him into a bigger conspiracy of a possible nuclear attack threat to the country by an extreme radical dirty scientist.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/916XWgTtWtL._AC_UL480_FMwebp_QL65_.jpg",
},
{ name:"Jurassic World",
price:"549",
starCount:0,
rating:"7.9",
about:"With Earth once again dominated by prehistoric predators, two generations of heroes must unite for a globe-spanning adventure to shape the destiny of humans and dinosaurs.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/81yI2kJmIEL._AC_UL480_FMwebp_QL65_.jpg",
},{ name:"REVOLT",
price:"499",
starCount:0,
rating:"9.3",
about:"Terminator meets Independence Day in this epic battle of Alien invasion. In the war-ravaged African countryside, aliens form an unlikely team to fight back, a U.S. soldier and a French foreign aid worker must team up to survive an alien onslaught. Their bond will be tested as they search for refuge across a crumbling world.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/81CGyVWrT1L._AC_UL480_FMwebp_QL65_.jpg",
},,
{ name:"The Roundup",
price:"719",
starCount:0,
rating:"8.8",
about:"Seven years after the roundup in Vietnam, Ma Seok-do joins a new squad to investigate a murder case. He soon starts to dig deeper when he finds out the case involves a synthetic drug and a gang of thugs.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/81y9QqhyAlL._AC_UL480_FMwebp_QL65_.jpg",
},
{ name:"Black Adam",
price:"499",
starCount:0,
rating:"9.7",
about:"Nearly 5,000 years after he was bestowed with the almighty powers of the ancient gods-and imprisoned just as quickly-Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/91Rv-Y8zRzL._AC_UL480_FMwebp_QL65_.jpg",
},
{ name:"Kandahar",
price:"389",
starCount:0,
rating:"6.2",
about:"A CIA Black Ops agent and his Afghan interpreter must evade deadly forces as they escape Iran after a whistleblower reveals the agent destroyed a nuclear facility.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/819OlsX85CL._AC_UL480_FMwebp_QL65_.jpg",
},
{ name:"Scream",
price:"999",
starCount:0,
rating:"8.7",
about:"The four survivors from the most recent Woodsboro Ghostface killings have moved to New York City for a fresh start. Just as they begin to feel a sense of normalcy, they receive that infamous call. Ghostface is more brutal and relentless than ever and will stop at nothing to hunt them down.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/81jV+c8KCHL._AC_UL480_FMwebp_QL65_.jpg",
},
{ name:"Sniper: The White Raven",
price:"259",
starCount:0,
rating:"7.8",
about:"Based on true events Mykola is an eccentric Ukrainian pacifist who wants to be useful to humanity. When Russia-Ukraine War begins in eastern Ukraine's region of Donbas in 2014, Mykola's naive world is collapsing as Russian soldiers kill his pregnant wife. With his peaceful life over and nothing left to live for, Mykola joins the Ukrainian Army.",
fav:false,
cart:false,
image:"https://m.media-amazon.com/images/I/71WlLo5s4aL._AC_UL480_FMwebp_QL65_.jpg",
}];
